### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by pmviva** [surajmandalcell/potato-dark#1]
Hi @surajmandalcell, I liked your theme and I was hoping to see multilingual support in it. I was planning on making a fork and implement it myself in order to make a pull request, if you like.

In the README you mention to make a fork of the develop branch but I couldn't find any, is there another repo or am I missing something?

**Comment by surajmandalcell** [comment]
crap, i did a recent rewrite and forgot to update readme :man_facepalming: , sorry for that ill do it in a instant. Thanks for your interest!
