### ISSUE TITLE
Theme broken on Hugo Website

### ISSUE THREAD

**Issue by onedrawingperday** [surajmandalcell/potato-dark#4]
Hello I am one of the maintainers of Hugo Themes.

Line 16 in this recent commit https://github.com/surajmandalcell/potato-dark/blame/master/layouts/partials/menu.html#L16 broke your theme's demo:

```
execute of template failed: template: partials/menu.html:16:20: executing "partials/menu.html" at <.Permalink>: can't evaluate field Permalink in type *navigation.MenuEntry
```

Furthermore you need to fix your theme for the breaking changes in Hugo v.0.57.0, you can find instructions in https://github.com/gohugoio/hugoThemes/issues/682

If you need help feel free to ask.

Also note that once gohugoio/hugoThemes#668 is addressed you will need to keep an eye on whether your theme demo generates on the Hugo website.

We are a very small team and we just cannot keep up opening issues in the various theme repositories. Whenever a theme demo breaks and remains broken then at some point it will be removed from the list without prior warning.

Thank you.

**Comment by surajmandalcell** [comment]
WIll fix this soon and will post an update on the issue page, thanks for notifying!

**Comment by onedrawingperday** [comment]
Thank you. Once you make a commit to fix the above feel free to close this issue.

**Comment by onedrawingperday** [comment]
@surajmandalcell 
Any updates on this issue? I am about to remove broken themes from the Hugo website and your theme is one of them.

If you don't have the time at the moment, then you can always re-submit your theme once it is fixed.

**Comment by surajmandalcell** [comment]
@onedrawingperday yes currently I don't have enough time to fix the theme so I'll just re-submit when when I fix this.

**Comment by surajmandalcell** [comment]
Hey @onedrawingperday please check the theme again and see if it is ready for re-submission. It works on my end.

**Comment by onedrawingperday** [comment]
@surajmandalcell 

I will review the theme once you submit it again at: https://github.com/gohugoio/hugoThemes/issues
