### ISSUE TITLE
Where's Demo Link? 

### ISSUE THREAD

**Issue by BayuAngora** [surajmandalcell/potato-dark#5]
Where's demo link?

**Comment by surajmandalcell** [comment]
Its broken due to latest hugo update, Check Issue#4
Here is a previous snapshot of the blog if you want
https://github.com/surajmandalcell/blog
https://surajmandalcell.github.io/blog/

**Comment by surajmandalcell** [comment]
This is a bit late I guess but anyhow, https://surajmandalcell.github.io/potato-dark/
